import type { Metadata } from "next";

import { Header } from "@/components/header/Header";
import { NextAuthSessionProvider } from "@/components/SessionProvider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"bg-stone-800 text-white flex flex-col"}>
        <NextAuthSessionProvider>
          <Header />
          <div className="p-4 flex flex-col">{children}</div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
