import type { Metadata } from "next";

import { NextAuthSessionProvider } from "@/components/SessionProvider";
import { Header } from "@/components/header/Header";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"flex flex-col bg-stone-800 text-white"}>
        <NextAuthSessionProvider>
          <Header />
          <div className="flex flex-col p-4">{children}</div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
